#!/usr/bin/python
# coding: utf-8

# Can enable debug output by uncommenting:
#import logging
#logging.basicConfig(level=logging.DEBUG)

import Adafruit_BMP.BMP085 as BMP085
import sys
import smbus

ADDRESS = 0x48
CHANNEL = 1

class ADT7410:
    def __init__(self, address, channel):
        self.address = address
        self.channel = channel

    # read from ADT7410
    def readValue(self):
        try:
            data = smbus.SMBus(self.channel).read_i2c_block_data(self.address, 0x00, 2)
            temp = (data[0] << 8 | data[1]) >> 3
            if(temp >= 4096):
                temp -= 8192
            value = temp * 0.0625
            return value
        except Exception as e:
            print str(e)
            return None

# ===========================================================================
# Munin Plugin - Temperature
# ===========================================================================

is_config = len(sys.argv) == 2 and sys.argv[1] == "config"

if is_config:
    print "graph_title Temperatur (I2C)"
    print "graph_vlabel Temperature(Celsius)"
    print "graph_category sensors"
    print "graph_ordor BMP180temp ADT7410temp HDC1000temp"
    #print "graph_scale no"
    #print "graph_args -A -Y"
    print "BMP180temp.label BMP180 Temp(C)"
    print "ADT7410temp.label ADT7410 Temp(C)"
else:
# Initialise the BMP085 and use STANDARD mode (default value)
    sensor1 = BMP085.BMP085()
    sensor2 = ADT7410(ADDRESS, CHANNEL)

    temp1 = sensor2.read_temperature()
    temp2 = sensor2.readValue()
#   pressure = sensor.read_pressure()
    print "BMP180temp.value %.2f" % temp1
    print "ADT7410temp.value %.2f" % temp2
