#!/usr/bin/python
# coding: utf-8

# Can enable debug output by uncommenting:
#import logging
#logging.basicConfig(level=logging.DEBUG)

import Adafruit_BMP.BMP085 as BMP085
import sys

# ===========================================================================
# Munin Plugin - Temperature
# ===========================================================================

is_config = len(sys.argv) == 2 and sys.argv[1] == "config"

if is_config:
    print "graph_title Temperatur (I2C)"
    print "graph_vlabel ℃"
    print "graph_category sensors"
    #print "graph_scale no"
    #print "graph_args -A -Y"
    print "temperature.label Temperatur (℃)"
else:
# Initialise the BMP085 and use STANDARD mode (default value)
    sensor = BMP085.BMP085()

    temp = sensor.read_temperature()
#   pressure = sensor.read_pressure()
    print "temperature.value %.2f" % temp
